import type { Account, Category, Transaction } from './types'

export const mockAccounts: Account[] = [
  {
    id: '1',
    name: 'Main Checking',
    type: 'BANK',
    currencyCode: 'USD',
    balance: 5420.5,
    isActive: true,
  },
  {
    id: '2',
    name: 'Savings',
    type: 'BANK',
    currencyCode: 'USD',
    balance: 12350.0,
    isActive: true,
  },
  {
    id: '3',
    name: 'Credit Card',
    type: 'CREDIT',
    currencyCode: 'USD',
    balance: -850.25,
    isActive: true,
  },
  {
    id: '4',
    name: 'Cash Wallet',
    type: 'CASH',
    currencyCode: 'USD',
    balance: 120.0,
    isActive: true,
  },
]

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Groceries',
    type: 'EXPENSE',
    color: '#10b981',
    icon: 'ShoppingCart',
  },
  {
    id: '2',
    name: 'Transportation',
    type: 'EXPENSE',
    color: '#3b82f6',
    icon: 'Car',
  },
  {
    id: '3',
    name: 'Entertainment',
    type: 'EXPENSE',
    color: '#8b5cf6',
    icon: 'Film',
  },
  {
    id: '4',
    name: 'Utilities',
    type: 'EXPENSE',
    color: '#f59e0b',
    icon: 'Zap',
  },
  {
    id: '5',
    name: 'Dining Out',
    type: 'EXPENSE',
    color: '#ef4444',
    icon: 'UtensilsCrossed',
  },
  {
    id: '6',
    name: 'Healthcare',
    type: 'EXPENSE',
    color: '#ec4899',
    icon: 'Heart',
  },
  {
    id: '7',
    name: 'Shopping',
    type: 'EXPENSE',
    color: '#06b6d4',
    icon: 'ShoppingBag',
  },
  { id: '8', name: 'Salary', type: 'INCOME', color: '#22c55e', icon: 'Wallet' },
  {
    id: '9',
    name: 'Freelance',
    type: 'INCOME',
    color: '#14b8a6',
    icon: 'Briefcase',
  },
  {
    id: '10',
    name: 'Investments',
    type: 'INCOME',
    color: '#a855f7',
    icon: 'TrendingUp',
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'EXPENSE',
    fromAccountId: '1',
    categoryId: '1',
    amount: 125.5,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    description: 'Grocery shopping',
    note: 'Weekly grocery shopping',
  },
  {
    id: '2',
    type: 'EXPENSE',
    fromAccountId: '3',
    categoryId: '5',
    amount: 45.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    description: 'Restaurant',
    note: 'Lunch with team',
  },
  {
    id: '3',
    type: 'INCOME',
    toAccountId: '1',
    categoryId: '8',
    amount: 3500.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    description: 'Salary',
    note: 'Monthly salary',
  },
  {
    id: '4',
    type: 'EXPENSE',
    fromAccountId: '1',
    categoryId: '2',
    amount: 60.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    description: 'Gas station',
    note: 'Gas station',
  },
  {
    id: '5',
    type: 'EXPENSE',
    fromAccountId: '3',
    categoryId: '3',
    amount: 25.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    description: 'Movie tickets',
    note: 'Movie tickets',
  },
  {
    id: '6',
    type: 'TRANSFER',
    fromAccountId: '1',
    toAccountId: '2',
    amount: 500.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    description: 'Transfer to savings',
    note: 'Monthly savings',
  },
  {
    id: '7',
    type: 'EXPENSE',
    fromAccountId: '1',
    categoryId: '4',
    amount: 150.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    description: 'Electric bill',
    note: 'Electric bill',
  },
  {
    id: '8',
    type: 'INCOME',
    toAccountId: '1',
    categoryId: '9',
    amount: 800.0,
    currencyCode: 'USD',
    occurredAt: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    note: 'Freelance project',
  },
]
